# coding: utf-8

"""
    Alertmanager API

    API of the Prometheus Alertmanager (https://github.com/prometheus/alertmanager)  # noqa: E501

    OpenAPI spec version: 0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.postable_alerts import PostableAlerts  # noqa: E501
from swagger_client.rest import ApiException


class TestPostableAlerts(unittest.TestCase):
    """PostableAlerts unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPostableAlerts(self):
        """Test PostableAlerts"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.postable_alerts.PostableAlerts()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
