# coding: utf-8

"""
    Alertmanager API

    API of the Prometheus Alertmanager (https://github.com/prometheus/alertmanager)  # noqa: E501

    OpenAPI spec version: 0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.silence_api import SilenceApi  # noqa: E501
from swagger_client.rest import ApiException


class TestSilenceApi(unittest.TestCase):
    """SilenceApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.silence_api.SilenceApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_delete_silence(self):
        """Test case for delete_silence

        """
        pass

    def test_get_silence(self):
        """Test case for get_silence

        """
        pass

    def test_get_silences(self):
        """Test case for get_silences

        """
        pass

    def test_post_silences(self):
        """Test case for post_silences

        """
        pass


if __name__ == '__main__':
    unittest.main()
