# coding: utf-8

"""
    Alertmanager API

    API of the Prometheus Alertmanager (https://github.com/prometheus/alertmanager)  # noqa: E501

    OpenAPI spec version: 0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.matchers import Matchers  # noqa: E501
from swagger_client.rest import ApiException


class TestMatchers(unittest.TestCase):
    """Matchers unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testMatchers(self):
        """Test Matchers"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.matchers.Matchers()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
